### ISSUE TITLE
mindmap generation failed

### ISSUE THREAD

**Issue by alvin-xu** [TomWright/mermaid-server#137]
Try to generate the mindmap by the api, but failed.  can anyone knows the reason of syntax issue or others ?

```sh
curl --location --request POST 'http://127.0.0.1:80/generate?type=png' \
--header 'Content-Type: text/plain' \
--output tmp.png \
--data-raw '
mindmap
  root((mindmap))
    Origins
      Long history
      ::icon(fa fa-book)
      Popularisation
        British popular psychology author Tony Buzan
    Research
      On effectivness<br/>and features
      On Automatic creation
        Uses
            Creative techniques
            Strategic planning
            Argument mapping
    Tools
      Pen and paper
      Mermaid
'
```

```log
2024/10/13 02:14:03 [500] could not generate diagram: cachingGenerater.generate failed: failed when executing mermaid: exit status 1: Generating single mermaid chart
: 
Error: Evaluation failed: Error: Parse error on line 1:
mindmap  root((mind
^
Expecting 'open_directive', 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
    at pptr://__puppeteer_evaluation_script__:13:17
    at ExecutionContext._ExecutionContext_evaluate (file:///root/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:225:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (file:///root/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:104:16)
    at async ElementHandle.evaluate (file:///root/node_modules/puppeteer-core/lib/esm/puppeteer/common/JSHandle.js:86:16)
    at async ElementHandle.$eval (file:///root/node_modules/puppeteer-core/lib/esm/puppeteer/common/ElementHandle.js:138:24)
    at async renderMermaid (file:///root/node_modules/@mermaid-js/mermaid-cli/src/index.js:197:22)
    at async parseMMD (file:///root/node_modules/@mermaid-js/mermaid-cli/src/index.js:172:20)
    at async run (file:///root/node_modules/@mermaid-js/mermaid-cli/src/index.js:403:20)
    at async cli (file:///root/node_modules/@mermaid-js/mermaid-cli/src/index.js:138:3)
```

**Comment by diraneyya** [comment]
Fixed, check #140
